
export const SET_LOADING = "SET_LOADING";
export const SET_USER_STATE = "SET_USER_STATE";
export const SAVE_USER_STATE = "SAVE_USER_STATE";
export const SAVE_USER_STATE_SUCCESS = "SAVE_USER_STATE_SUCCESS";
export const SAVE_USER_STATE_FAILURE = "SAVE_USER_STATE_FAILURE";

export const USER_LOGOUT_STATE = "USER_LOGOUT_STATE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_LOGIN_STATE = "USER_LOGIN_STATE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const GET_USER_STATE = "GET_USER_STATE";
export const GET_USER_STATE_SUCCESS = "GET_USER_STATE_SUCCESS";
export const GET_USER_STATE_FAILURE = "GET_USER_STATE_FAILURE";

export const SEND_REQUEST_STATE = "SEND_REQUEST_STATE";
export const SEND_REQUEST_STATE_SUCCESS = "SEND_REQUEST_STATE_SUCCESS";
export const SEND_REQUEST_STATE_FAILURE = "SEND_REQUEST_STATE_FAILURE";

export const SET_REQUEST_STATE = "SET_REQUEST_STATE";
export const GET_REQUEST_STATE = "GET_REQUEST_STATE";
export const GET_REQUEST_STATE_SUCCESS = "GET_REQUEST_STATE_SUCCESS";
export const GET_REQUEST_STATE_FAILURE = "GET_REQUEST_STATE_FAILURE";

export const GET_FOLLOWERS_STATE = "GET_FOLLOWERS_STATE";
export const GET_FOLLOWERS_STATE_SUCCESS = "GET_FOLLOWERS_STATE_SUCCESS";
export const GET_FOLLOWERS_STATE_FAILURE = "GET_FOLLOWERS_STATE_FAILURE";
export const GET_FOLLOWINGS_STATE = "GET_FOLLOWINGS_STATE";
export const GET_FOLLOWINGS_STATE_SUCCESS = "GET_FOLLOWINGS_STATE_SUCCESS";
export const GET_FOLLOWINGS_STATE_FAILURE = "GET_FOLLOWINGS_STATE_FAILURE";

export const UPDATE_REQUEST_STATE = "UPDATE_REQUEST_STATE";
export const UPDATE_REQUEST_STATE_SUCCESS = "UPDATE_REQUEST_STATE_SUCCESS";
export const UPDATE_REQUEST_STATE_FAILURE = "UPDATE_REQUEST_STATE_FAILURE";
